### PR TITLE
Vignette suggestions

### PR DESCRIPTION
**Pull request by grantmcdermott**
Hi Laurent,

Better late than never... Here are some suggested changes to the introductory vignette. I've focused predominantly on the section(s) related to interaction terms, given that these appear to be the main point of confusion for new users IME. As you'll see, I've broken these out into their own subsection and tried to work from there. I also include various other small changes that I think will help to clarify things for the modal reader.

Use, don't use, or feel free to close at your leisure!

### CODE REVIEW

**Comment by lrberge** [comment]
I've just read the changes: That really is ace Grant! That's much much better thanks!

I'll have a detailed look at the full vignette this week and very likely accept all. Thanks again!

**Comment by grantmcdermott** [comment]
Great! You've probably noticed the actions error because ggplot2 -- which I use for the staggered DiD heatmap --- isn't in imports.

I guess we have three options here, thinking about CRAN checks:

1. Add ggplot2 to imports so this heatmap doesn't cause an issue.
2. Redo the heatmap in base R (I'd need to read up how to do it nicely).
3. Drop the figure altogether, although I must say that I think it will help readers to understand the staggered setting better.

**Comment by lrberge** [comment]
Indeed, I was thinking to add `ggplot2` in the suggests (nice base R graphs take too many lines and are arcane).

**Comment by grantmcdermott** [comment]
Okay, cool. I pushed it alongside some minor typo fixes that I caught. If nothing else, let's see if any other unsuspected action errors turn up.

PS. My next trick is to convince you to adjust your html themes in the YAML to:
```
    theme: journal
    highlight: haddock
```
but I realise that may be a matter of taste!

**Comment by lrberge** [comment]
I've just went through the new vignette. It really reads well. 
Creating a new section for the interactions was a good idea, I underestimated the risk of confusion, now it makes it clear.

OK, commit the theme changes so that I can accept the PR ;-)

**Comment by grantmcdermott** [comment]
Done. I've changed the theme for this vignette. Let's see whether you like before changing any of the others.

**Comment by lrberge** [comment]
I wasn't clear but I did check it out and I like it!

Thanks again for the PR!

**Comment by lrberge** [comment]
Just to say that I've just pushed the new vignette to the website and I have added you as an author since you now wrote a fair share of it! Again, nice work! :-)

**Comment by grantmcdermott** [comment]
That's overly generous of you, but I suppose I shouldn't object too hard.

I have a few other (minor) ideas about other parts of the vignette, but will save that for our next call about the JSS paper. Thanks for merging!

**Pull request merged**
